config/routes.rb
Rancho::Application.routes.draw do
  resources :line_items

  resources :carts

  get "catalog/index"
  resources :htscdts

  root 'catalog#index', as: 'catalog'

  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add_htscdt(htscdt_id)
		current_item = line_items.find_by(htscdt_id: htscdt_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(htscdt_id: htscdt_id)
		end
		current_item
	end

end

app/models/htscdt.rb
class Htscdt < ActiveRecord::Base
	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	validates :htsus, :date, :author, :inv_description, :gen_eng_description, :gen_esp_description, :early_triggers, :legal_authority, :comments, :confidence, :image_url, 
						presence: true
	validates :image_url, 
						format: {
							with: %r{\.(gif|jpg|png)\Z}i, 
							message: 'must be a URL for GIF, JPG or PNG image.'
						}
	validates :htsus, uniqueness: true
	validates :htsus, format: { with: /\d{4}\.\d{2}\.\d{4}/, message: 'The HTSUS format is not correct' }
	validates :htsus, length: {is: 12, message: 'The HTSUS format is 12 characters max'}

	def self.latest
		Htscdt.order(:updated_at).last
	end

	private
		# ensure that there are no line items referencing this product
		def ensure_not_referenced_by_any_line_item
			if line_items.empty?
				return true
			else
				errors.add(:base, 'Line Items present')
				return false
		end
	end
	
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :htscdt
  belongs_to :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to catalog_url, notice: 'Your cart is empty' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to catalog_url, notice: 'Invalid URL'
    end
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  def index
  	@htscdts = Htscdt.order(:htsus)
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern
  
  private
  
    def set_cart
      @cart = Cart.find(session[:cart_id])
    
    rescue ActiveRecord::RecordNotFound
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
end

app/controllers/htscdts_controller.rb
class HtscdtsController < ApplicationController
  before_action :set_htscdt, only: [:show, :edit, :update, :destroy]

  # GET /htscdts
  # GET /htscdts.json
  def index
    @htscdts = Htscdt.all
  end

  # GET /htscdts/1
  # GET /htscdts/1.json
  def show
  end

  # GET /htscdts/new
  def new
    @htscdt = Htscdt.new
  end

  # GET /htscdts/1/edit
  def edit
  end

  # POST /htscdts
  # POST /htscdts.json
  def create
    @htscdt = Htscdt.new(htscdt_params)

    respond_to do |format|
      if @htscdt.save
        format.html { redirect_to @htscdt, notice: 'Htscdt was successfully created.' }
        format.json { render action: 'show', status: :created, location: @htscdt }
      else
        format.html { render action: 'new' }
        format.json { render json: @htscdt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /htscdts/1
  # PATCH/PUT /htscdts/1.json
  def update
    respond_to do |format|
      if @htscdt.update(htscdt_params)
        format.html { redirect_to @htscdt, notice: 'Htscdt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @htscdt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /htscdts/1
  # DELETE /htscdts/1.json
  def destroy
    @htscdt.destroy
    respond_to do |format|
      format.html { redirect_to htscdts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_htscdt
      @htscdt = Htscdt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def htscdt_params
      params.require(:htscdt).permit(:htsus, :date, :author, :verified_by, :inv_description, :gen_eng_description, :gen_esp_description, :early_triggers, :legal_authority, :la_link, :other_link, :comments, :confidence, :image_url)
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    htscdt = Htscdt.find(params[:htscdt_id])
    @line_item = @cart.add_htscdt(htscdt.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:htscdt_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/htscd_ts_helper.rb
module HtscdTsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
	
<h2>Your Invoice</h2>

<table>
	<% @cart.line_items.each do |item| %>
		<tr>
			<td><%= item.quantity %>&times;</td>
			<td><%= item.htscdt.gen_eng_description %></td>
			<td><%= item.htscdt.htsus %></td>
		</tr>
	<% end %>
</table>
<%= button_to 'Delete Invoice', @cart, method: :delete, data: { confirm: 'Are you sure you want to delete the invoice?' } %>

app/views/catalog/index.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<h1>HTSUS Catalog</h1>

<% cache ['catalog', Htscdt.latest] do %>
	<% @htscdts.each do |htscdt| %>
		<% cache ['entry', htscdt] do %>
			<div class="entry">
				<%= image_tag(htscdt.image_url) %>
				<div class="htsus">
					<h3><%= link_to htscdt.htsus, htscdt %><br/> <%=  %></h3>
				</div>
				<div class="title">
					<h4><%= htscdt.gen_eng_description %></h4>
				</div>
				<div class="price_line">
					<span class="price"><%= htscdt.inv_description %></span>
        	<span class="price"><%= htscdt.gen_esp_description %></span>
      	</div>
      	<%= sanitize(htscdt.comments) %>	
				<div class="price_line">
					<span class="info"><%= htscdt.author %> | </span>
					<span class="info"><%= htscdt.verified_by %> | </span>
					<span class="info"><%= htscdt.date.to_time.strftime('%B %e %Y') %></span>
					<%= button_to 'Add to Invoice', line_items_path(htscdt_id: htscdt) %>
				</div>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/htscdts/_form.html.erb
<%= form_for(@htscdt) do |f| %>
  <% if @htscdt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@htscdt.errors.count, "error") %> prohibited this htscdt from being saved:</h2>

      <ul>
      <% @htscdt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :htsus %><br>
    <%= f.text_field :htsus %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :verified_by %><br>
    <%= f.text_field :verified_by %>
  </div>
  <div class="field">
    <%= f.label :inv_description %><br>
    <%= f.text_field :inv_description %>
  </div>
  <div class="field">
    <%= f.label :gen_eng_description %><br>
    <%= f.text_field :gen_eng_description %>
  </div>
  <div class="field">
    <%= f.label :gen_esp_description %><br>
    <%= f.text_field :gen_esp_description %>
  </div>
  <div class="field">
    <%= f.label :early_triggers %><br>
    <%= f.text_field :early_triggers %>
  </div>
  <div class="field">
    <%= f.label :legal_authority %><br>
    <%= f.text_field :legal_authority %>
  </div>
  <div class="field">
    <%= f.label :la_link %><br>
    <%= f.text_field :la_link %>
  </div>
  <div class="field">
    <%= f.label :other_link %><br>
    <%= f.text_field :other_link %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :confidence %><br>
    <%= f.text_field :confidence %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/htscdts/edit.html.erb
<h1>Editing htscdt</h1>

<%= render 'form' %>

<%= link_to 'Show', @htscdt %> |
<%= link_to 'Back', htscdts_path %>

app/views/htscdts/index.html.erb
<h1>HTS Classifications</h1>

<table>
  <% @htscdts.each do |htscdt| %>
  <tr class="top_line">
    <td> <%= image_tag(htscdt.image_url, class: 'list_image') %> </td>
    <td class="list_columns">
      <dl>
        <dt><%= htscdt.htsus %></dt>
        <dd><%= htscdt.inv_description %></dd>
        <dd><%= htscdt.gen_eng_description %></dd>
        <dd><%= htscdt.gen_esp_description %></dd>
      </dl>
    </td>

    <td class="list_columns">
      <dl>
        <dt><%= htscdt.author %></dt>
        <dd><%= htscdt.verified_by %></dd>
        <dd><%= htscdt.legal_authority %></dd>
        <dd><%= link_to 'Link To Reference', htscdt.la_link, :target => "_blank"  unless htscdt.la_link.empty? %></dd>
      </dl>
    </td>

    <td class="list_columns">
      <dl>
        <dt><%= htscdt.early_triggers %></dt>
        <dd><%= htscdt.date.to_time.strftime('%B %e %Y') %></dd>
        <dd><%= htscdt.confidence %></dd>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Edit', edit_htscdt_path(htscdt) %><br/>
      <%= link_to 'Destroy', htscdt, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>

  <tr class="list_line">
    <td></td>
    <td class="list_comments" colspan = "4">
      <dt>COMMENTS<dt>
      <dd><%= sanitize(htscdt.comments) %></dd>
      <dd><%= link_to 'Other Link References', htscdt.other_link, :target => "_blank" unless htscdt.other_link.empty? %></dd>
    </td>
  </td>
  <td class="list_actions"></td>
  <% end %>
</table>

<br />

<%= link_to 'New HTSCDT', new_htscdt_path %>

app/views/htscdts/new.html.erb
<h1>New htscdt</h1>

<%= render 'form' %>

<%= link_to 'Back', htscdts_path %>

app/views/htscdts/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>


<h1><%= @htscdt.htsus %></h1>

<table>
  <tr class="top_line">
    <td> <%= image_tag(@htscdt.image_url, class: 'list_image') %> </td>
    <td class="list_columns">
      <dl>
        <dt><%= @htscdt.htsus %></dt>
        <dd><%= @htscdt.inv_description %></dd>
        <dd><%= @htscdt.gen_eng_description %></dd>
        <dd><%= @htscdt.gen_esp_description %></dd>
      </dl>
    </td>

    <td class="list_columns">
      <dl>
        <dt><%= @htscdt.author %></dt>
        <dd><%= @htscdt.verified_by %></dd>
        <dd><%= @htscdt.legal_authority %></dd>
        <dd><%= link_to 'Link To Reference', @htscdt.la_link, :target => "_blank"  unless @htscdt.la_link.empty? %></dd>
      </dl>
    </td>

    <td class="list_columns">
      <dl>
        <dt><%= @htscdt.early_triggers %></dt>
        <dd><%= @htscdt.date.to_time.strftime('%B %e %Y') %></dd>
        <dd><%= @htscdt.confidence %></dd>
      </dl>
    </td>
  </tr>

  <tr class="list_line">
    <td></td>
    <td class="list_comments" colspan = "4">
      <dt>COMMENTS<dt>
      <dd><%= sanitize(@htscdt.comments) %></dd>
      <dd><%= link_to 'Other Link References', @htscdt.other_link, :target => "_blank" unless @htscdt.other_link.empty? %></dd>
    </td>
  </td>
</table>



<%= link_to 'Back', catalog_path %>

app/views/layouts/application.html.erb
<html>
	<head>
	<title>Rancho Customs Brokers HTSCDT</title>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
 	<body class="<%= controller.controller_name %>">
		<div id="banner">
			<%= link_to image_tag("rancho_logo.jpg"), "/" %>
			<%= @page_title || "RANCHO CUSTOMS BROKERS HTSCDT" %>
		</div>
 		<div id="columns">
			<div id="side">
				<ul>
					<li><a href="http://www....">Home</a></li>
					<li><a href="http://www..../faq">Questions</a></li>
					<li><a href="http://www..../news">News</a></li>
					<li><a href="http://www..../contact">Contact</a></li>
				</ul>
			</div>
			<div id="main">
 				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :htscdt %><br>
    <%= f.text_field :htscdt %>
  </div>
  <div class="field">
    <%= f.label :cart %><br>
    <%= f.text_field :cart %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Htscdt</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.htscdt %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Htscdt:</strong>
  <%= @line_item.htscdt %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>